### ISSUE TITLE
Can't release the selection when click on the different line

### ISSUE THREAD

**Issue by benebsiny** [niuware/mui-rte#176]
## Checklist

- [X] This is not covered in the [repository examples](https://github.com/niuware/mui-rte/tree/master/examples).
- [X] I am using the package [latest version](https://github.com/niuware/mui-rte/releases/latest).
- [X] This is a bug report or an enhancement proposal.

## Description

When I select a text, then I click on the different line, the selection can't be released, but if I click on the same line, it would be released. See demo

![](https://i.imgur.com/4IIVBBe.gif)

### Code to reproduce
**JSX**
```jsx
<div className="editor-box">
  <MUIRichTextEditor {...props} />
</div>
```
**SCSS**
```scss
.editor-box {
  border: #a1a1a1 1px solid;
  border-radius: 5px;
  height: 450px;

  .MUIRichTextEditor-editorContainer-8 {
    position: relative;
    margin-left: 10px;
    height: 380px;
    overflow: auto;
  }
}

```

**Comment by benebsiny** [comment]
I found a solution, change the SCSS like the following.
```scss
$editor-height: 380px;
#mui-rte-editor-container {
    margin-left: 20px;
    overflow: auto;
    width: calc(100% - 20px);
    height: $editor-height;
    .DraftEditor-root {
      height: $editor-height - 10px;
      .DraftEditor-editorContainer {
        height: $editor-height - 10px;
        .public-DraftEditor-content {
          height: $editor-height - 10px;
        }
      }
    }
  }
```
And it solved.
